---
language: en
version: "0.2"
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - words
words:
  - autoclean
  - autoremove
  - backrefs
  - Bru≈æina
  - buildx
  - codespell
  - containerd
  - Coreutils
  - darktable
  - digikam
  - direnv
  - drawio
  - exfat
  - exfatprogs
  - flathub
  - flatpak
  - flatpakrepo
  - gitleaks
  - gitlint
  - hwinfo
  - inet
  - insertafter
  - kdiff3
  - kget
  - krename
  - krusader
  - Kubuntu
  - kwin
  - lineinfile
  - markdownlint
  - nftables
  - nodev
  - nosuid
  - opensfx
  - openttd
  - passwordless
  - Pylance
  - rawtherapee
  - roadmap
  - shellib
  - subelements
  - sudoer
  - tmpfs
  - Widelands
  - Xebis
flagWords: []
